name: Deploy Automatic
on:
  workflow_run:
    workflows: ["Test"]
    types:
      - completed

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy-beta:
    if: ${{ github.ref_name == 'channel/beta' }} # If the branch is channel/beta, auto deploy to beta
    runs-on: ubuntu-latest
    steps:
      - run: echo "Deploying on beta...."

  deploy-stage:
    if: startsWith(github.ref, 'release')
    runs-on: ubuntu-latest
    steps:
      - run: echo "Deploying on stage...."

  deploy-prod:
    if: ${{ github.ref_name == 'main' }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "Deploying on prod...."  