name: Finish Release
on: 
  workflow_dispatch
env:
  GITHUB_TOKEN: ${{ secrets.TOKEN }}

jobs:
  create-pr-from-release-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: create pull request
        
        run: |
          git status
          ls -latr
          echo ${{ secrets.TOKEN }}
          echo $GITHUB_TOKEN | gh auth login --with-token
          gh pr create -B develop -H release/v1.0.0 --title 'Merge release/v1.0.0 into develop' --body 'Created by Github action'
        