name: Finish Release
on: 
  workflow_dispatch
env:
  GITHUB_TOKEN: ${{ secrets.TOKEN }}

jobs:
  create-pr-from-release-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: create pull request        
        run: |
          gh auth status
          gh pr create -B develop -H channel/beta --title 'Merge channel/beta into develop' --body 'Created by Github action'
        