name: Finish Release
on: 
  workflow_dispatch:
  push:
    types: [created]
    branches:
      - 'releases/**'

jobs:
  create-pr-from-release-branch:
    if: github.event.push.created
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: create pull request  
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}      
        run: |
          gh pr create -B main -H release/v1.0.2 --title 'Merge release/v1.0.2 into develop' --body 'Created by Github action'
        