name: Finish Release
on: 
  workflow_dispatch:
  create:

jobs:
  create-pr-from-release-branch:
    if: startsWith(github.ref, 'release/v')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: create pull request  
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}      
        run: |
          gh pr create -B main -H release/v1.0.3 --title 'Merge release/v1.0.3 into develop' --body 'Created by Github action'
        