name: Finish Release
on: 
  workflow_dispatch


jobs:
  create-pr-from-release-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: create pull request  
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}      
        run: |
          gh pr create -B main -H channel/beta --title 'Merge channel/beta into develop' --body 'Created by Github action'
        