name: Release
on: 
  workflow_dispatch:
    inputs:
      version:
        type: string
        description: Version of the release

jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - name: Bump version
        run: |
          echo "Version: ${{ github.event.inputs.version }}"

  # create-pr-from-release-branch:
  #   if: ${{ contains(github.ref, 'refs/heads/release/') }}
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: create pull request  
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.TOKEN }}      
  #       run: |
  #         gh pr create -B main -H release/${GITHUB_REF##*/} --title 'Merge into Main' --body 'Created by Github action'
        